#!/usr/bin/env bash
# Writes the Homebrew formula for one release to standard output.
#
# Usage: generate-formula.sh VERSION DIST_DIR
#
# DIST_DIR must hold the archives built by the publish workflow, named
# collapse-VERSION-OS-ARCH.tar.gz, for darwin and linux on amd64 and arm64.
# The formula installs these prebuilt binaries, which brew downloads from the
# GitHub release v<VERSION>.
set -euo pipefail

version="$1"
dist="$2"
repo="${GITHUB_REPOSITORY:-ziqul/collaps-output-by-pattern}"
base_url="https://github.com/${repo}/releases/download/v${version}"

sha() {
  sha256sum "${dist}/collapse-${version}-$1.tar.gz" | cut -d' ' -f1
}

cat <<FORMULA
# This file is generated by .github/scripts/generate-formula.sh in
# https://github.com/${repo} on every push to main. Do not edit it by hand.
class Collapse < Formula
  desc "Collapse lines of piped output that match given substrings into one line"
  homepage "https://github.com/${repo}"
  version "${version}"

  on_macos do
    on_arm do
      url "${base_url}/collapse-${version}-darwin-arm64.tar.gz"
      sha256 "$(sha darwin-arm64)"
    end
    on_intel do
      url "${base_url}/collapse-${version}-darwin-amd64.tar.gz"
      sha256 "$(sha darwin-amd64)"
    end
  end

  on_linux do
    on_arm do
      url "${base_url}/collapse-${version}-linux-arm64.tar.gz"
      sha256 "$(sha linux-arm64)"
    end
    on_intel do
      url "${base_url}/collapse-${version}-linux-amd64.tar.gz"
      sha256 "$(sha linux-amd64)"
    end
  end

  def install
    bin.install "collapse"
  end

  test do
    assert_match "Usage: collapse", shell_output("#{bin}/collapse -h 2>&1")
  end
end
FORMULA
