#!/usr/bin/env bash
# Writes the Homebrew formula for one commit to standard output.
#
# Usage: generate-formula.sh VERSION COMMIT_SHA
#
# The formula builds collapse from source at the given commit, so no binary is
# built or uploaded anywhere.
set -euo pipefail

version="$1"
revision="$2"
repo="${GITHUB_REPOSITORY:-ziqul/collaps-output-by-pattern}"

cat <<FORMULA
# This file is generated by .github/scripts/generate-formula.sh in
# https://github.com/${repo} on every push to main. Do not edit it by hand.
class Collapse < Formula
  desc "Collapse lines of piped output that match given substrings into one line"
  homepage "https://github.com/${repo}"
  url "https://github.com/${repo}.git",
      revision: "${revision}"
  version "${version}"
  head "https://github.com/${repo}.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w")
  end

  test do
    assert_match "Usage: collapse", shell_output("#{bin}/collapse -h 2>&1")
  end
end
FORMULA
